SET FOREIGN_KEY_CHECKS=0;

CREATE DATABASE TIENESHUECO;
USE TIENESHUECO;

CREATE TABLE USUARIO (
    CORREO  varchar(50) NOT NULL PRIMARY KEY,
    PASS    varchar(20) NOT NULL,
    NOMBRE  varchar(20) NOT NULL
);

CREATE TABLE ENCUESTA (
    ID      varchar(32) NOT NULL PRIMARY KEY,
    PROPIETARIO varchar(50) NOT NULL,

    FOREIGN KEY (PROPIETARIO) REFERENCES USUARIO(CORREO)
);

CREATE TABLE FECHA (
    IDENCUESTA  varchar(32) NOT NULL,
    FECHA   date NOT NULL,
    INDEX (FECHA),

    FOREIGN KEY (IDENCUESTA) REFERENCES ENCUESTA(ID),
    CONSTRAINT PKFECHA PRIMARY KEY (IDENCUESTA, FECHA)
);

CREATE TABLE HORA (
    IDENCUESTA  varchar(32) NOT NULL,
    FECHA   date NOT NULL,
    HORAINICIO  TIME NOT NULL,
    HORAFIN     TIME NOT NULL,

    FOREIGN KEY (IDENCUESTA) REFERENCES FECHA(IDENCUESTA),
    FOREIGN KEY (FECHA) REFERENCES FECHA(FECHA),
    CONSTRAINT PKHORA PRIMARY KEY (IDENCUESTA, FECHA, HORAINICIO, HORAFIN)
);